behaviors:
  DodgeBall:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048 #1024
      buffer_size: 10240 #20480
      learning_rate: 0.0003 #0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true #false
      hidden_units: 256 #512
      num_layers: 2 #3
      vis_encode_type: simple
      goal_conditioning_type: none
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0
    keep_checkpoints: 40
    checkpoint_interval: 1000000 #2000000
    max_steps: 50000000 #500000000
    time_horizon: 500 #1000
    summary_freq: 5 #50000
    threaded: false
    self_play:
      save_steps: 500000
      team_change: 500000 #1000000
      swap_steps: 200000
      window: 100
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0

# Enable when training from a build or in the cloud.
#  env_settings:
#    num_envs: 3